---
title: "UAS"
author: "Lenka Miková"
format: html
editor: visual
---

# Basics

## Fotogrammetrie a geometrie snímání

Jedná se o metodu získávání přesných prostorových informací o objektech na zemském povrchu pomocí fotografických snímků. Snímky zpravidla pořiovány v centrální projekci, kde je středem promítání střed optického systému (objektivu). Centrální projekce snímku se pak převádí na ortogonální projekci.

**Centrální projekce** - každý bod skutečné scény je promítnutý na senzor fotoaparátu skrz jeden konkrétní bod (střed objektivu - střed optického systému). Znamená to, že každý bod v krajině je spojen "paprskem" který prochází středem objektivu. Na druhé straně pak tento paprsek dopadá na snímkovou rovinu.

**Převod na ortogonální projekci** - Centrální projekce způsobuje zkreslení (vzdálené objekty se zdají menší, rozměry a úhly nejsou zachovány). V ortogonální projekci jsou všechny body zobrazovány kolmo („z ptačí perspektivy“), tedy každý bod terénu se promítá na snímek po kolmici k rovině snímku. Výsledkem je ortofotografie (ortofoto), kde rozměry i polohy odpovídají skutečnosti, jako na mapě.

Důležité pro fotogrammetrii jsou prvky vnitřní a vnější orientace neboť určují, jak je snímek vytvořen a jak je umístěn v prostoru.

**Prvky vnitřní orientace** popisují vztah mezi středem promítání a rovinou snímku. Určuje parametry kamery jenž ovlivňují tvorbu obrazu a lze jej získat z kalibračního protokolu (či od výrobce kamery).Jedná se o: - ohniskovou vzdálenost - poloha hlavního bodu - distorze obrazu (způsobena distorzí optiky); optická vada vznikající vlastností čočky - vzdálenost a poloha rámových značek

**Distorze obrazu** vzniká vlivem vlastností čočky a projevuje se deformací výsledného obrazu (soudkovitost - vyboulení, poduškovitost - stlačení). Díky této optické vadě nebude obraz přesně odpovídat realitě.

**Prvky vnější orientace** charakterizují kde se snímací zařízení nacházelo v terénu v okamžiku expozice a jak bylo natočeno vzhledem k souřasnému systému. Určují vztah mezi kamerou a reálným světem a jsou nezbytná pro následnou georeferenci snímku. Určují se z GNSS či IMU jednotek. Jedná se o: - souřadnice polohy - směr a orientace

## UAS a UAV

**UAS** (*Unmanned Aerial Systems*) zahrnuje UAV, pozemní řídící stanici, senzory a podůrný SW.

**UAV** (*Unmanned Aerial Vehicle*) neboli bezpilotní stroj lze rozdělit podle velikosti (mikro, mini, malé), typu pohonu (letadlo, vrtulník, multikoptéra) nebo použitého senzoru (RGB, multispektralní, hyperspektrální, LiDARové, termální).

# Data processing

Lze rozdělit do několika základních kroku:

1.  Nalezení klíčových bodů (SIFT, GCP)

2.  Vypočítání pozice a orientace snímku (SfM)

3.  Vytvoření hustého bodového mračna z řídkého bodového mračna (MVS)

4.  Tvorba digitální modelu

5.  Ortorektifikace snímků a tvorba bezešvé mozaiky

## SIFT

**SIFT** (*Scale Invariant Feature Transform*) je algoritmus, jenž zvládne najít dostatečný poče spolehlivých prvků pro využití k párování snímků. SIFT pro to využívá GCP neboli také vlícovací body.

## GCP

**GCP** (*Ground Control Point*) jsou body na zemském povrchu s přesně známými souřadnicemi, které se využívají pro georeferencování dat získaných zejména v letecké fotogrammetrii a při zpracování dronových snímků pomocí SfM.

Jedná se o místa, jenž jsou fyzicky označena (terčem nebo křížem), jejich přesná poloha (X, Y, Z) je určena pomocí přesného geodetického měření (GPS/GNSS). Body jsou rozmístěny rovnoměrně v oblasti zájmu, měly by být viditelné na vícero snímcích a souřadnice těchto bodů se vkládají do zpracovatelského SW. Přínosem GCP je výrazné zvýšení absolutní prostorové přesnosti výsledného modelu i ortofotomapy.

## SfM

**SfM** (*Structure for Motion*) je fotogrammetrická metoda určená k rekonstrukci trojrozměrné struktury z dvourozměrných obrazů, typicky fotografií pořízených z různých úhlů a pozic. Výstupem je řídké mračno bodů a trajektorie polohy kamery.

Princip spočívá v tom, že specializovaný SW automaticky vyhledá společné znaky (body, rysy) na jednotlivých snímcích, odhaduje pozici a orientaci kamery pro každý snímek, a následně z těchto informací vybduje 3D model povrchu nebo objektu.

## MVS

MVS (*Multi-view stereo*) zahušťuje řídké bodové mračno, přičemž umí pracovat s velmi vysokým množstvím snímků s odlišnými úhly záběru. Jeho cílem je rekonstruovat kompletní prostorový model s využitím vstupních snímků o známé poloze. Oproti SfM musí MVS znát prvky vnitřní a vnější orientace vstupních snímků. Velmi špatně funguje v prostoru s dokonalým rozptylem světla (lambertovské potvrchy).


